### PR TITLE
Fix featured image modal behaviour

### LINKED ISSUE #75: Featured image not working properly with Replace Image button
@roborourke Not entirely sure what is happening here but when I go and click on the Featured Image after setting it I get a different image if I decide to go and click on "Replace Image".

Also possibly related the bounding box issue. I've posted both in here for you to see. Happy to help you test if required.
Kapture 2020-08-13 at 14 58 55

Kapture 2020-08-13 at 15 03 09

Here is the bounding box issue again.
Kapture 2020-08-13 at 15 58 06

### PR DESCRIPTION
**Pull request by roborourke**
There are still some elements I'd like to tidy up such as the toolbar showing on the image selection view but this update now at least keeps the sidebar and edit mode in sync.

It seems to behave much more consistently now eg. clicking an existing featured image should open on the edit mode, clicking "replace image" should open on the image selection view.

Media library still works the same and the image block is still working alright.

I refactored the messy event callback approach into the extended media frame backbone `View`. This allows for a late escape hatch when sometimes the frame selection hasn't been populated yet but we can add the edit state later on when the frame is ready instead.

Fixes #75 (hopefully)

### CODE REVIEW

**Comment by roborourke** [comment]
@stuartshields would you be able to test this branch out for me? You might need to clone in place of the copy in the `vendor` directory. If you use composer just note you'll need to run the build steps eg. `npm i && npm run build`.

This might not actually solve the bounding box errors thinking about it further so let me know if you're still getting that issue.

**Comment by abhishek-kaushik** [comment]
Tested the changes on Altis V4 looks good to me
CC: @stuartshields

**Comment by roborourke** [comment]
@abhishek-kaushik did it fix the bounding box issues with the cropping UI as well?

**Comment by abhishek-kaushik** [comment]
@roborourke , no. Sorry. That is not fixed
Skadoosh 2020-08-17 at 17 02 50

**Comment by roborourke** [comment]
@abhishek-kaushik can you create a separate issue for that one but detailing the way that other image upload field is implemented? eg. CMB2 or whatever. How can we reproduce it?

**Pull request merged**
